import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a7c8fd",
        "on-primary-container": "#7596c8",
        "on-primary-fixed": "#001c3b",
        "on-primary-fixed-variant": "#254875",
        "on-error-container": "#93000a",
        "tertiary-container": "#182f43",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-container": "#785a1a",
        "surface": "#f7f9fb",
        "tertiary-fixed-dim": "#b2c9e2",
        "gold-muted": "#B8860B",
        "secondary-container": "#fed488",
        "on-secondary-fixed-variant": "#5d4201",
        "on-error": "#ffffff",
        "gold-leaf": "#D4AF37",
        "surface-dim": "#d8dadc",
        "text-secondary": "#475569",
        "inverse-primary": "#a7c8fd",
        "navy-vibrant": "#003366",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "background": "#f7f9fb",
        "outline-variant": "#c3c6d0",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#3e5f8e",
        "primary-container": "#002d59",
        "surface-bright": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#33495e",
        "error": "#ba1a1a",
        "outline": "#737780",
        "on-secondary": "#ffffff",
        "surface-border": "#E2E8F0",
        "primary": "#001835",
        "tertiary-fixed": "#cee5ff",
        "inverse-surface": "#2d3133",
        "status-success": "#10B981",
        "surface-container-high": "#e6e8ea",
        "text-primary": "#0F172A",
        "status-warning": "#F59E0B",
        "secondary": "#775a19",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#261900",
        "on-surface-variant": "#43474f",
        "on-tertiary-container": "#8097af",
        "primary-fixed": "#d5e3ff",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#011a2d",
        "inverse-on-surface": "#eff1f3",
        "status-error": "#EF4444",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#041d30",
        "secondary-fixed": "#ffdea5",
        "navy-deep": "#001F3D",
        "surface-container-highest": "#e0e3e5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-desktop": "24px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "gutter-mobile": "16px",
        "margin-desktop": "40px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "title-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [tailwindcssAnimate],
}
